# Production Docker Compose Configuration
# Complete stack with Django, Nginx, PostgreSQL, and Redis

services:
  nginx:
    build:
      context: .
      dockerfile: docker/production/nginx/Dockerfile
    image: kore-nginx:latest
    container_name: kore-nginx-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    volumes:
      - static_volume:/static:ro
      - media_volume:/media:rw
    networks:
      - kore-prod-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/api/v1/health/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  django:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    image: kore-django:latest
    container_name: kore-django-prod
    restart: always
    expose:
      - "8000"
    env_file:
      - .envs/.production/.django
      - .envs/.production/.postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - kore-prod-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: kore-postgres-prod
    restart: always
    expose:
      - "5432"
    env_file:
      - .envs/.production/.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kore-prod-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: kore-redis-prod
    restart: always
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - kore-prod-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  kore-prod-network:
    driver: bridge
